host: 0.0.0.0
port: 8080
service_name: __API_NAME__
protocols:
    http: true
    http2: true
    grpc: true
    jsonrpc: true
    security:
        auth:
            enabled: true
            type: apikey
            header_name: X-API-Key
            query_name: api_key
            api_keys: {}
